### ISSUE TITLE
Summary will not load

### ISSUE THREAD

**Issue by stevepopovich** [HcwXd/better-medium-stats#1]
Hi! Nice extension. I find Medium's stats really frustrating and literally googled "Better Medium Stats" and found this. Awesome and I really appreciate how you matched the motif of Medium in the extension. 

That being said, my summary tab is not loading. I have restarted Chrome to no avail. Any suggestions?

Is there any debugging I can do? Not sure how to `right click -> inspect` on an extension.

Thanks for your time!

**Comment by blogumi** [comment]
Also broken for me

**Comment by agostontorok** [comment]
Not working for me either

**Comment by stevepopovich** [comment]
Leaving this open, but it works for me 40% of the time. Better than nothing. For those still looking for a better stats experience, I would suggest Medium Enhanced Stats, it is gorgeous: https://medium.com/blogging-guide/medium-enhanced-stats-chrome-extension-5a98e60be194

**Comment by HcwXd** [comment]
Hi @stevepopovich @blogumi @agostontorok 

Sorry for the late reply and thank you all for reporting the issue.

Since the summary tab is working for my Medium account, I'd really appreciate it if you can share some screenshots or more details about the problem. To help debug the problem, you can also`right click` -> `inspect` on the popout of this extension.

I will also try to investigate this issue. Again, thanks for using better-medium-stats.

**Comment by agostontorok** [comment]
Hi, I get this:

DevTools failed to load SourceMap: Could not load content for
chrome-extension://pdehepohihkkmeclfnlnipieffkomajc/style.css.map: HTTP
error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

It sometimes loads the Summary (that is the only occasion I see this
inspect output) but then becomes unresponsive and I can't click on anything
else.

Hope this helps, would love to use the extension.
--
Ágoston Török
*http://agostontorok.github.io/ <http://agostontorok.github.io/>*


Cheng-Wei Hu <notifications@github.com> ezt írta (időpont: 2020. máj. 25.,
H, 11:43):

**Comment by mikecm1** [comment]
@stevepopovich @agostontorok @HcwXd @blogumi 

I just get the stats for a guy named "Mark Magelky"... Pretty bizarre.
